### ISSUE TITLE
How to run Emulator

### ISSUE THREAD

**Issue by nikolay-borzov** [ASchoe311/LaunchMate#3]
I'm trying to configure [the following trick](https://www.reddit.com/r/playnite/comments/gstw58/comment/fsgk7o7/) to launch HTML file in a separate Firefox instance

> by creating an emulator definition for Firefox associated with HTML files. The emulator definition creates a unique Firefox profile per game and has Firefox launch a new process. This lets Playnite's playtime tracking work perfectly. And creating a new Firefox profile directory inside the game installation directory makes it easy to backup a game save.

> Firefox emulator definition:
> - Executable: C:\...\firefox.exe
> - Arguments: -new-instance -profile "{InstallDir}/firefox-profile" "{ImagePath}"
> - Supported Filetypes: html,htm

![image](https://github.com/user-attachments/assets/4eda4541-4bcd-4dd9-b309-b70365487d33)

For the game I have a single ROM set pointing to a HTML file

After hitting play:

![image](https://github.com/user-attachments/assets/881cad30-0ffa-4a0c-bb49-2dc70fc2485c)

**Comment by ASchoe311** [comment]
Based on the screenshot, this issue is unrelated to LaunchMate. The error received is from Playnite itself and seems as though there is something wrong with the way you have the emulator launch action set up.

**Comment by ASchoe311** [comment]
Based on the screenshot, this issue is unrelated to LaunchMate. The error received is from Playnite itself and seems as though there is something wrong with the way you have the emulator launch action set up.

**Comment by nikolay-borzov** [comment]
I thought LaunchMate can be used to configure emulator action like this:

![image](https://github.com/user-attachments/assets/6b4feb75-ff6f-4d89-b560-d846b7abcfe2)

**Comment by ASchoe311** [comment]
In theory I guess it could, however that error message is not being sent by LaunchMate. The error message you're receiving is from Playnite itself about your launch configuration for this game entry. 

If you could explain a bit more what you're trying to accomplish, I may be able to help.

**Comment by nikolay-borzov** [comment]
I try to run an HTML page using Firefox that uses new instance and a separate profile

The game:
- Has no actions
- Has index.html at the `{InstallDir}`
- Has platform "PC (Windows)"

Other parameters are:

- App Type: Launch an App
- App Path: `C:\Program Files\Mozilla Firefox\firefox.exe`
- App Parameters: `-new-instance -profile "{InstallDir}/firefox-profile" "{InstallDir}/index.html"`
- Launch Group Enabled: True
- Auto-Close: True

The game is among "Matched Games"

There are several problems:
1. Playnite requires at least one Action to perform "Play". It means LaunchMate won't get control if the game has no actions
2. LaunchMate doesn't replace `{InstallDir}` by install directory full path inside "App Parameters"

Is it possible
1. To expand [Playnite varibales](https://api.playnite.link/docs/manual/advanced/gameVariables.html) inside "App Parameters" fields
2. To ignore Playnite restriction regarding "Play" Action
?

**Comment by ASchoe311** [comment]
For the problems: 

1.  This is intended behavior. LaunchMate will not take action if no game can be launched
2.  At this time, functionality for expanding Playnite variables has not been implemented

For the questions:

1. I will look into implementing this in the next version
2. This I will not implement as it does not fit with the intended behavior of LaunchMate or Playnite. If Playnite considers there to be an error, LaunchMate will not act. LaunchMate is not meant as a replacement for Playnite's game launching, it is meant to perform actions alongside those launches that would typically need to be accomplished by writing a script.

Given all that, it seems your best course of action here would be to stick with launching your firefox instance using Playnite's default emulator launch configuration.

I sincerely appreciate you taking the time to run through this with me, though. I hope you are able to find some other use for LaunchMate in the future.
